version: '3.8'

services:
  proxy-server:
    build: .
    container_name: proxy-server
    ports:
      - "4000:4000"
    environment:
      - LEETCODE_SESSION=${LEETCODE_SESSION}
      - CSRFTOKEN=${CSRFTOKEN}
    restart: unless-stopped
